name: CI

on:
  push: 
    branches: [ main, master ]
  pull_request:
    branches: [main, master ]

jobs:
  # test code pushed
  check-pull-request:
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run all tests
        run: | 
          npm install
          npm run test

