name: Deploy to EC2

on:
  push:
    branches:
      # replace my branch to the branch where you want to deploy
      - my_branch

jobs:
  # test code pushed
  check-pull-request:
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: | 
          npm install
          npm run test
  # build
  build-and-deploy:
    needs: [check-pull-request]
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Add Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Application
        run: npm install
      - name: Deploy to cloud
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: "${{ secrets.SSH_REMOTE_PATH }}"
          remote_host: "${{ secrets.SSH_REMOTE_HOST }}"
          remote_user: " ${{ secrets.SSH_REMOTE_USER }}"
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
